package com.tcl.srm.control.common;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-26T21:52:13.570+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EsbServiceImplService",
                  wsdlLocation = "http://10.117.159.28:8080/tms/services/esbService?wsdl",
                  targetNamespace = "http://common.control.srm.tcl.com/")
public class EsbServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://common.control.srm.tcl.com/", "EsbServiceImplService");
    public final static QName EsbServiceImplPort = new QName("http://common.control.srm.tcl.com/", "EsbServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.117.159.28:8080/tms/services/esbService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EsbServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.117.159.28:8080/tms/services/esbService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EsbServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EsbServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EsbServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EsbServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EsbServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EsbServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EsbService
     */
    @WebEndpoint(name = "EsbServiceImplPort")
    public EsbService getEsbServiceImplPort() {
        return super.getPort(EsbServiceImplPort, EsbService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EsbService
     */
    @WebEndpoint(name = "EsbServiceImplPort")
    public EsbService getEsbServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EsbServiceImplPort, EsbService.class, features);
    }

}
