
package com.tcl.srm.control.common;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-26T21:52:13.536+08:00
 * Generated source version: 3.2.7
 *
 */
public final class EsbService_EsbServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://common.control.srm.tcl.com/", "EsbServiceImplService");

    private EsbService_EsbServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EsbServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

//        Thread.currentThread().setContextClassLoader(EsbService_EsbServiceImplPort_Client.class.getClassLoader());
        EsbServiceImplService ss = new EsbServiceImplService(wsdlURL, SERVICE_NAME);
        EsbService port = ss.getEsbServiceImplPort();

        {
        System.out.println("Invoking dataExchange...");
        String _dataExchange_jsonObject = "\n" +
                "{reqJsonObj: {DELIVERY_INFO: [{ZTPNO: 10280818120052,BUS_NUM: 黑A19914,DRIVER: 佟宏元,DRIVER_MOBILE: 18804040404,ID_NO: 321000321000123000,IN_TIME: 2018-12-17 04:12:17,DESTINATION: 新工厂E栋5区三楼,RECEPTIONIST: 张三,RECEPTIONIST_MOBILE: 18804603878,REMARK: ,STATUS: Y,FOLLOWER: [{FOLLOWER_NAME: 一号,FOLLOWER_ID_NO: 321000321000123001}, {FOLLOWER_NAME: 二号,FOLLOWER_ID_NO: 321000321000123002}, {FOLLOWER_NAME: 三号,FOLLOWER_ID_NO: 321000321000123003}, {FOLLOWER_NAME: 四号,FOLLOWER_ID_NO: 321000321000123004}]}]},reqMsgId: 40001,reqSystemId: SRM}";
        String _dataExchange__return = port.dataExchange(_dataExchange_jsonObject);
        System.out.println("dataExchange.result=" + _dataExchange__return);


        }

        System.exit(0);
    }

}
