
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.tcl.srm.control.common;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-26T21:52:13.552+08:00
 * Generated source version: 3.2.7
 *
 */

@WebService(
                      serviceName = "EsbServiceImplService",
                      portName = "EsbServiceImplPort",
                      targetNamespace = "http://common.control.srm.tcl.com/",
                      wsdlLocation = "http://10.117.159.28:8080/tms/services/esbService?wsdl",
                      endpointInterface = "com.tcl.srm.control.common.EsbService")

public class EsbServiceImplPortImpl implements EsbService {

    private static final Logger LOG = Logger.getLogger(EsbServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.tcl.srm.control.common.EsbService#dataExchange(java.lang.String jsonObject)*
     */
    public String dataExchange(String jsonObject) {
        LOG.info("Executing operation dataExchange");
        System.out.println(jsonObject);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
