
package cn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EsbService", targetNamespace = "http://common.control.srm.tcl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EsbService {


    /**
     * 
     * @param jsonObject
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dataExchange", targetNamespace = "http://common.control.srm.tcl.com/", className = "cn.DataExchange")
    @ResponseWrapper(localName = "dataExchangeResponse", targetNamespace = "http://common.control.srm.tcl.com/", className = "cn.DataExchangeResponse")
    public String dataExchange(
            @WebParam(name = "jsonObject", targetNamespace = "")
                    String jsonObject);

}
