
package cn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EsbServiceImplService", targetNamespace = "http://common.control.srm.tcl.com/", wsdlLocation = "http://10.117.159.28:8080/tms/services/esbService?wsdl")
public class EsbServiceImplService
    extends Service
{

    private final static URL ESBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ESBSERVICEIMPLSERVICE_QNAME = new QName("http://common.control.srm.tcl.com/", "EsbServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.117.159.28:8080/tms/services/esbService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ESBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EsbServiceImplService() {
        super(__getWsdlLocation(), ESBSERVICEIMPLSERVICE_QNAME);
    }

    public EsbServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESBSERVICEIMPLSERVICE_QNAME, features);
    }

    public EsbServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ESBSERVICEIMPLSERVICE_QNAME);
    }

    public EsbServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESBSERVICEIMPLSERVICE_QNAME, features);
    }

    public EsbServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EsbServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EsbService
     */
    @WebEndpoint(name = "EsbServiceImplPort")
    public EsbService getEsbServiceImplPort() {
        return super.getPort(new QName("http://common.control.srm.tcl.com/", "EsbServiceImplPort"), EsbService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EsbService
     */
    @WebEndpoint(name = "EsbServiceImplPort")
    public EsbService getEsbServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://common.control.srm.tcl.com/", "EsbServiceImplPort"), EsbService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ESBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ESBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
